

CREATE TABLE TripData (
    RouteID INT PRIMARY KEY AUTO_INCREMENT,
    StartingDestination VARCHAR(255) NOT NULL,
    EndDestination VARCHAR(255) NOT NULL,
    StopDestination VARCHAR(255) NOT NULL,
    Distance INTEGER NOT NULL, 
    TripTime INTEGER NOT NULL, 
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL
);
